version: '2'
services:
    omnibus-deb:
        build: ./build/deb
        image: netsil/omnibus-deb:latest
        volumes:
            - ./:/root/omnibus-netsil-collectors/:rw
            - /var/cache/omnibus:/var/cache/omnibus:rw
    omnibus-rpm:
        build: ./build/rpm
        image: netsil/omnibus-rpm:latest
        volumes:
            - ./:/root/omnibus-netsil-collectors/:rw
            - /var/cache/omnibus:/var/cache/omnibus:rw
    omnibus-deb-test:
        build: ./test/deb
        volumes:
            - ./pkg:/root/pkg:ro
    omnibus-rpm-test:
        build: ./test/rpm
        volumes:
            - ./pkg:/root/pkg:ro

