#!/bin/sh
#
# Perform necessary netsil setup steps
# after package is installed.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# NOTE: The logic for postinst will be moved into install_netsil_collectors.sh

#netsil_install_dir=/opt/netsil/collectors
# Run supervisor
#${netsil_install_dir}/embedded/bin/python ${netsil_install_dir}/embedded/lib/python2.7/site-packages/supervisor/supervisord.py -c ${netsil_install_dir}/conf.d/netsil-collectors.conf

echo "Thank you for installing netsil!"

exit 0
