#!/bin/sh
#
# Perform necessary netsil setup steps
# after package is installed.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Make start.sh and stop.sh executable
chmod +x /opt/netsil/collectors/start.sh
chmod +x /opt/netsil/collectors/stop.sh

echo "Thank you for installing netsil!"

exit 0
