#!/bin/sh
#
# Perform necessary netsil removal steps
# after package is uninstalled.
#

# Remove everything in the collectors directory
rm -rf /opt/netsil/collectors

# TODO: Remove sslproxy's named pipe and the trusted cert we installed, as well as the iptables rules
echo "netsil has been uninstalled!"

exit 0
