#!/bin/sh
#
# Perform necessary netsil setup steps
# before package is installed.
#

echo "You're about to install netsil!"

# Stop any existing netsil-collectors
if [ -f /var/run/netsil-supervisord.pid ] ; then 
    kill -15 $(cat /var/run/netsil-supervisord.pid)
    sleep 3
fi

# Install certificate for sslproxy, create iptables rules, and also create a named pipe for sslsplit --> rpcapd
