#!/bin/sh
#
# Perform necessary netsil setup steps
# prior to installing package.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# First, stop supervisor
kill -15 $(cat /var/run/netsil-supervisord.pid)

# Wait for supervisor to tear stuff down
sleep 3

# Then, remove everything in the collectors directory
rm -rf /opt/netsil/collectors

exit 0
