#!/bin/sh
#
# Perform necessary netsil setup steps
# prior to installing package.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Stop supervisor and sleep
if [ -f /var/run/netsil-supervisord.pid ] ; then
    kill -15 $(cat /var/run/netsil-supervisord.pid)
    sleep 3
fi

# Remove everything in the collectors directory
rm -rf /opt/netsil/collectors

exit 0
